<?php
namespace Application\Page;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-29 at 16:26:50.
 */
class LoginTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Login
     */
    protected $login;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->login = new Login;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Application\Page\Login::_main
     * @todo   Implement test_main().
     */
    public function test_main() {
        $this->assertTrue(true);
    }

    /**
     * @covers Application\Page\Login::_entrar
     * @todo   Implement test_entrar().
     */
    public function test_entrar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Application\Page\Login::_sair
     * @todo   Implement test_sair().
     */
    public function test_sair() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Application\Page\Login::_recover
     * @todo   Implement test_recover().
     */
    public function test_recover() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Application\Page\Login::_sendPassword
     * @todo   Implement test_sendPassword().
     */
    public function test_sendPassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Application\Page\Login::_updatepassword
     * @todo   Implement test_updatepassword().
     */
    public function test_updatepassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
